[readable]
cv_imshow_title = Object Detection Tools for Yolov3, Yolov4, Yolov5
video_true_webcam_false = True
video_screenshots_path_folder = /_screenshoots/
video_save_path_folder = /_outputs/
video_path_file = /_videos/robloxapp.wmv
selected_class_id = 7

[changeable]
last_frame = 15
split_percentage_valid = 20

