[readable]
cv_imshow_title = Data Preprocessing and CV Skills
video_screenshots_path_folder = /_screenshoots/
video_save_path_folder = /_outputs/
model_main_yolov5 = ../yolov5
model_main_deepsort = ../deep_sort_realtime
video_true_webcam_false = True
video_path_file = /_videos/all_17-18-19_port_pas_23hataliport_.mp4
selected_class_id = 0

[changeable]
last_frame = 518
split_percentage_valid = 20
split_type_yolov3_yolov5 = 1
split_max_class_count = 3

